# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visible2',
            field=models.BooleanField(default=True),
        ),
    ]
