# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_visible2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='visible2',
        ),
    ]
