# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160323_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='source_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fashion',
            name='source_link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tech',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tech',
            name='source_link1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tech',
            name='source_link2',
            field=models.CharField(max_length=300),
        ),
    ]
