# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_articlecomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlecomment',
            old_name='created_date',
            new_name='cr_date',
        ),
    ]
